object Version {
  val ascender           = "0.1"
  val akka               = "2.4.3"
  val akkaHttp           = "10.0.3"
  val hikariCP           = "3.1.1"
  val postgres           = "9.4-1201-jdbc41"
  val scala              = "2.11.8"
  val scalaTest          = "2.2.6"
  val slf4j              = "1.6.4"
  val akkaHttpCors       = "0.1.11"
  val akkaSlf4j          = "2.4.11"
  val ammoniteOps        = "0.7.0"
  val commonsIO          = "2.5"
  val scopt              = "3.5.0"
  val shapeless          = "2.2.5"
  val circe              = "0.7.0"
  val akkaHttpCirce      = "1.12.0"
  val quill              = "1.1.0"
}
